AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with nestjs.

Resources:
  GlobalDashboardUrlGenerator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-url-generator
      Handler: dist/lambda-entry-point.handler
      Runtime: nodejs14.x
      CodeUri: deploy/nest-lambda.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60